# Generated by Django 4.2.3 on 2023-08-02 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_remove_suppliers_cos"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="amount",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
