# Generated by Django 4.2.3 on 2023-08-05 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0006_supplieritems"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplieritems",
            old_name="cItem",
            new_name="sItem",
        ),
    ]
