# Generated by Django 4.2.3 on 2023-08-09 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0009_customeritems_invoice_item_orders_saleprice_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Orders",
        ),
    ]
